services:


  oracle-db:

    image: gvenzl/oracle-free:23-slim

    environment:

      ORACLE_PASSWORD: oracle

      APP_USER: hotel

      APP_USER_PASSWORD: hotel123


    ports:

      - "1521:1521"


    volumes:

      - oracle-data:/opt/oracle/oradata


    healthcheck:

      test: ["CMD", "healthcheck.sh"]

      interval: 10s

      timeout: 5s

      retries: 10



  hotel-booking-app:

    image: hotel-booking-app:latest


    depends_on:

      oracle-db:

        condition: service_healthy


    ports:

      - "8080:8080"


    environment:

      SPRING_PROFILES_ACTIVE: docker



volumes:

  oracle-data: