version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-free:23-slim
    container_name: hotel-oracle-db

    ports:
      - "1521:1521"

    environment:
      ORACLE_PASSWORD: password
      APP_USER: hotel
      APP_USER_PASSWORD: hotel123

    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: