spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: hotel
    password: hotel123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        globally_quoted_identifiers: false
        format_sql: true

jwt:
  secret: my-super-secret-key-my-super-secret-key-123456
  expiration: 86400000